title = "sudoer"
baseURL = "http://localhost:1313"
languageCode = "es-pe"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "es"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "My personal blog"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/Prometeo"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-gray"
  featured_image = "images/banner.jpg"
  recent_posts_number = 2
